id: I44426F7A
ocr_import_info:
  timestamp: '2023-10-07T14:08:05.346880+00:00'
  batch_id: batch-6358
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-08 13:07:41.869559+00:00
last_modified: 2023-10-08 13:07:41.869565+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23444
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23444
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སྒམ་པོ་པ།
  languages:
  - bo
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9626128827956429
  ocr_word_median_confidence_index: 0.998667
bases:
  I1987:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1987
      total_pages: 505
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1987.txt
    statistics:
      ocr_word_median_confidence_index: 0.999188
      ocr_word_mean_confidence_index: 0.9663759729321472
  I1988:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1988
      total_pages: 499
      volume_number: 2
      volume_pages_bdrc_intro: 0
    order: 2
    base_file: I1988.txt
    statistics:
      ocr_word_median_confidence_index: 0.99788725
      ocr_word_mean_confidence_index: 0.9586223624834715
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
